Repository DU4L/CTFNote, pull requests merged in 2022-02, with the labels that each got.

#31 Add ical Link
  api/.env.dev
  api/.lintstagedrc.json
  api/migrations/41-ical-link.sql
  api/package.json
  api/src/index.ts
  api/src/routes/ical.ts
  api/yarn.lock
  front/.gitignore
  front/.lintstagedrc.json
  front/graphql.schema.json
  front/nginx.conf
  front/package.json
  front/quasar.conf.js
  front/src/components/Admin/Registration.vue
  front/src/components/Admin/Users.vue
  front/src/components/Auth/Register.vue
  front/src/components/CTF/Calendar.vue
  front/src/components/CTF/Guests.vue
  front/src/components/Menu/BaseMenuBar.vue
  front/src/ctfnote/models.ts
  front/src/ctfnote/settings.ts
  front/src/generated/graphql.ts
  front/src/graphql/Profile.graphql
  front/src/graphql/Settings.graphql
  front/src/pages/Admin.vue
  front/src/pages/Settings.vue
Labels: enhancement

#34 ical combining (extension of #31)
  .gitignore
  api/migrations/41-ical-link.sql
  docker-compose.yml
  front/nginx.conf
  ical-relay/Dockerfile
  ical-relay/config/config.toml
Labels: dependencies

#47 Hotfix: golang-ical branch change
  ical-relay/Dockerfile
Labels: bug, dependencies

#54 Dependabot/follow redirects 1.14.8
  api/yarn.lock
  front/yarn.lock
Labels: dependencies
